name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 */2 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Test
      run: go test -v ./...

  build:
    name: Build and Run
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Build
      run: go build -v -o cf2dns cmd/main.go
    - name: Create config file
      run: |
        cat > config.yaml <<EOF
        cf_url: "${{ secrets.CF_URL }}"
        cf_domain: "${{ secrets.CF_DOMAIN }}"
        cf_names: ${{ secrets.CF_NAMES }}
        gcore_url: "${{ secrets.GCORE_URL }}"
        gcore_domain: "${{ secrets.GCORE_DOMAIN }}"
        gcore_names: ${{ secrets.GCORE_NAMES }}
        cloudflare_api_token: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
        max_delay: ${{ secrets.MAX_DELAY }}
        EOF
    - name: Run DNS updater
      run: ./cf2dns
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cf2dns-logs
        path: '*.log'
        retention-days: 7