name: Update DNS Records

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' # 使用最接近你生产环境中 Go 版本的版本

    - name: Build go binary
      run: go build -o dns

    - name: Run go binary
      env:
        CLOUDFLARE_API_TOKEN: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
        GCORE_URL: ${{ secrets.GCORE_URL }}
        GCORE_DOMAIN: ${{ secrets.GCORE_DOMAIN }}
        GCORE_NAMES: ${{ vars.GCORE_NAMES }}
        CF_URL: ${{ secrets.CF_URL }}
        CF_DOMAIN: ${{ secrets.CF_DOMAIN }}
        CF_NAMES: ${{ vars.CF_NAMES }}
      run: chmod +x dns && ./dns --cloudflare-api-token $CLOUDFLARE_API_TOKEN --gcore-url=$GCORE_URL --gcore-domain $GCORE_DOMAIN --gcore-names $GCORE_NAMES --cf-domain $CF_DOMAIN --cf-names $CF_NAMES --cf-url=$CF_URL
