name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 */12 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Test
      run: go test -v ./...

  build:
    name: Build and Run
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Build
      run: go build -v -o cf2dns cmd/main.go
    - name: Create config file
      run: |
        cat > config.yaml <<EOF
        cloudflare:
          url: "${{ secrets.CLOUDFLARE_URL }}"
          domain: "${{ secrets.CLOUDFLARE_DOMAIN }}"
          names: ${{ secrets.CLOUDFLARE_NAMES }}
        gcore:
          url: "${{ secrets.GCORE_URL }}"
          domain: "${{ secrets.GCORE_DOMAIN }}"
          names: ${{ secrets.GCORE_NAMES }}
        maxDelay: ${{ secrets.MAX_DELAY }}
        cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        EOF
    - name: Run DNS updater
      run: ./cf2dns
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cf2dns-logs
        path: '*.log'
        retention-days: 7